[package]
name = "guest_code_for_zk_proof"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
cometbls-groth16-verifier = { path = "../../lib/cometbls-groth16-verifier" }
risc0-zkvm = { version = "1.1.1", default-features = false, features = ['std'] }
hex-literal = "0.4.1"
