[workspace]
resolver = "2"
members = ["host", "methods", "lib/cometbls-groth16-verifier"]

# Always optimize; building and running the guest takes much longer without optimization.
[profile.dev]
opt-level = 3

[profile.release]
debug = 1
lto = true
